twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        appName: "Ride Easy"
        currency: " CFA"
        codepays: "+33"
        concepteur: "By conception"
        appEmail: "contact@rideeasy.fr"
        appPhone: "+33 (0)7 56 81 80 77"
        phone: "+33 01 87 66 61 28"
        appAdresse: "Bessengue-Douala, Cameroun"
        bayesite: "https://www.bayeconception.com/"
        bayeemail: "contact@bayeconception.com"
        app_environement: '%env(APP_ENV)%'
        baye: "Baye conception"

when@test:
    twig:
        strict_variables: true
